INSERT INTO ATTENDEE (FIRST_NAME, LAST_NAME)
VALUES ('Jose', 'Gonzalez');

SELECT * FROM ATTENDEE;

-- Multiple INSERTs
INSERT INTO ATTENDEE (FIRST_NAME, LAST_NAME, PHONE, EMAIL, VIP)
VALUES
('Jon', 'Skeeter',4802185842,'john.skeeter@rex.net',1),
('Sam', 'Scala',2156783401,'sam.scala@gmail.com', 0),
('Brittany', 'Fisher',5932857296,'brittany.fisher@outlook.com', 0);

/* INSERT records using results from a SELECT query
INSERT INTO ATTENDEE (FIRST_NAME, LAST_NAME, PHONE, EMAIL)
SELECT FIRST_NAME, LAST_NAME, PHONE, EMAIL
FROM SOME_OTHER_TABLE;
*/

INSERT INTO COMPANY (NAME, DESCRIPTION, PRIMARY_CONTACT_ATTENDEE_ID)
VALUES ('RexApp SOlutions', 'A mobile app delivery service', 5);

INSERT INTO COMPANY (NAME, DESCRIPTION, PRIMARY_CONTACT_ATTENDEE_ID)
VALUES ('RexApp Solutions', 'A mobile app delivery service', 3);

DELETE FROM ATTENDEE
WHERE PHONE IS NULL
AND EMAIL IS NULL;

SELECT * FROM ATTENDEE
WHERE PHONE IS NULL
AND EMAIL IS NULL;

-- MySQL
TRUNCATE TABLE ATTENDEE;

UPDATE ATTENDEE SET EMAIL = UPPER(EMAIL);

UPDATE ATTENDEE SET FIRST_NAME = UPPER(FIRST_NAME),
LAST_NAME = UPPER(LAST_NAME);

UPDATE ATTENDEE SET VIP = 1
WHERE ATTENDEE_ID IN (3,4);

-- DROP TABLE MY_UNWANTED_TABLE;