CREATE TABLE ROOM (
ROOM_ID         INTEGER PRIMARY KEY AUTOINCREMENT,
FLOOR_NUMBER    INTEGER NOT NULL,
SEAT_CAPACITY   INTEGER NOT NULL
);

CREATE TABLE PRESENTATION (
PRESENTATION_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
BOOKED_COMPANY_ID      INTEGER NOT NULL,
BOOKED_ROOM_ID         INTEGER NOT NULL,
START_TIME             TIME,
END_TIME               TIME
);

CREATE TABLE ATTENDEE (
ATTENDEE_ID INTEGER         PRIMARY KEY AUTOINCREMENT,
FIRST_NAME  VARCHAR (30)    NOT NULL,
LAST_NAME   VARCHAR (30)    NOT NULL,
PHONE       INTEGER,
EMAIL       VARCHAR (30),
VIP         BOOLEAN         DEFAULT (0)
);

CREATE TABLE PRESENTATION_ATTENDANCE (
TICKET_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
PRESENTATION_ID  INTEGER,
ATTENDEE_ID      INTEGER
); 

SELECT
COMPANY.NAME as BOOKED_COMPANY,
ROOM.ROOM_ID as ROOM_NUMBER,
ROOM.FLOOR_NUMBER as FLOOR,
ROOM.SEAT_CAPACITY as SEATS,
START_TIME,
END_TIME

FROM PRESENTATION

INNER JOIN COMPANY
ON PRESENTATION.BOOKED_COMPANY_ID = COMPANY.COMPANY_ID

INNER JOIN ROOM
ON PRESENTATION.BOOKED_ROOM_ID = ROOM.ROOM_ID;

/* SELECT * FROM PRESENTATION_VW
WHERE SEAT_CAPACITY >= 30; */